version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/gtmapp?schema=public # Note: within Docker network, database:5432 is correct
      - JWT_SECRET=development-secret-key-change-in-production
      - NODE_ENV=development
      - PORT=3001

  database:
    image: postgres:14
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gtmapp
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: